### ISSUE TITLE
Implement Replace missing .csv data page

### ISSUE THREAD

**Issue by kennethcassel** [kennethcassel/usepandas#12]
Easy first time PR for someone.

Task:

 

- [ ] Create a python pandas code snippet that shows an example of replacing missing values in a .csv file. You can show a few different snippets with different options (i.e. replace all missing values with a fixed number, or replace with one dependent on the other values in the row). 
 

- [ ] Add code snippet to the file https://github.com/kennethcassel/usepandas/blob/master/src/docs/csv/replace-missing-data.mdx

 

- [ ] Add some comments explaining the code snippet(s). SImilar to the Sort .csv example.

 

- [ ] Verify project runs and builds locally. You should be able to see your code at localhost:8000/csv/replace-missing-data

**Comment by rohitgeddam** [comment]
I would like to do this.

**Comment by kennethcassel** [comment]
Go for it @rohitgeddam ! Let me know if you need any assistance. To start the project you will need to have gatsby installed. 

Once you have gatsby installed, just run `gatsby develop` in the root directory of the project and you should be able to see your changes at localhost:8000

**Comment by vinrok** [comment]
Hey folks! I am working on adding n rows.

**Comment by kennethcassel** [comment]
Awesome @vinrok! Glad to have the help :)

**Comment by vinrok** [comment]
Hey @kennethcassel can you help? Like when I am running-
``` gatsby develop``` command it throws error **fatal error process out of memory**.
How shall I debug it?

**Comment by santiviquez** [comment]
Hi @kennethcassel! I just submitted a PR for this issue: https://github.com/kennethcassel/usepandas/pull/26

**Comment by kennethcassel** [comment]
Merged thanks @santiviquez!
